source ~/.zplug/init.zsh

export HISTFILE=~/.histfile
export HISTSIZE=1000000 # internal number for history list items
export SAVEHIST=1000000 # maximum number of items for history file

setopt HIST_IGNORE_ALL_DUPS # do not put duplicated command into history list
setopt HIST_SAVE_NO_DUPS  # do not save duplicated commands
setopt HIST_REDUCE_BLANKS # remove unnecessary blanks
setopt INC_APPEND_HISTORY_TIME # append command to history file immediately after execution
setopt EXTENDED_HISTORY # record command start time
setopt EXTENDED_GLOB

zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"

if ! zplug check --verbose; then
    printf "Install ? [yN]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
  fi

# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

source ~/.zwilliam

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
PROG=sg source /Users/william/.sourcegraph/sg.zsh_autocomplete

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/william/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/william/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/william/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/william/google-cloud-sdk/completion.zsh.inc'; fi
