#!/bin/zsh
# vim: set filetype=bash : */ ~
# User configuration
export SRC="$HOME/code"

# fzf exports
export FZF_DEFAULT_COMMAND="fdfind -t f"

export SSH_KEY_FOLDER="$HOME/.ssh/keys"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# correct locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# nice terminal colours
export TERM=xterm-256color
export BAT_THEME="zenburn"

# set preffered editor
export VISUAL="nvim"
export EDITOR="nvim"


function cond_source() {
    file=$1
    alternative=$2

    if [[ -a $file ]]; then
        source $file
    elif [[ -a $alternative ]]; then
        source $alternative
    fi
}

function cond_eval() {
    cmd=$1
    expression="$2"

    if type $cmd &> /dev/null; then
        result=$(eval $expression)
        eval $result
    fi
}

# For Nix
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
else
  cond_source "${HOME}/.fzf.zsh"
fi
cond_source /usr/local/opt/fzf/shell/completion.zsh /usr/share/doc/fzf/examples/completion.zsh
cond_source /usr/local/opt/fzf/shell/key-bindings.zsh /usr/share/doc/fzf/examples/key-bindings.zsh

export SDKMAN_DIR="$HOME/.sdkman"
cond_source $HOME/.sdkman/bin/sdkman-init.sh

cond_eval "pyenv" "pyenv init --path"
cond_eval "direnv" "direnv hook zsh"
cond_eval "zoxide" "zoxide init zsh"

# Setup environment by executing funcs

cond_eval "starship" "starship init zsh"

# enable vim mode
bindkey -v

# enable 'vv' in vim mode to open vim
autoload edit-command-line ; zle -N edit-command-line
bindkey -M vicmd v edit-command-line
# if we're in our work environment then load work scripts
# otherwise just load normal scripts
if [[ -a ~/.work ]]; then
    scripts=$SRC/dotfiles/scripts.d/*.bash
else
    scripts=$SRC/dotfiles/scripts.d/^work*.bash
fi

# # in zsh =~ means:
# # = -> perform word splitting
# # ~ -> perform globbing
for file in $=~scripts; do
    source $file
done

export PATH="$SRC/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
