#!/bin/zsh
# vim: set filetype=bash : */ ~
# User configuration
export SRC="$HOME/code"

# fzf exports
export FZF_DEFAULT_COMMAND="fdfind -t f"

export SSH_KEY_FOLDER="$HOME/.ssh/keys"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PATH:$SRC/bin"
export PATH="$PATH:$HOME/.local/bin"

# aliases

# Preferred editor for local and remote sessions
export EDITOR='nvim'
export VISUAL='nvim'

# correct locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# nice terminal colours
export TERM=xterm-256color

if type "fdfind" &> /dev/null; then
    alias fd='fdfind'
fi

if type "tmux-next" &> /dev/null; then
    alias tmux='tmux-next -2' #tmux installed from ppa named its binary tmux-next
fi


function cond_source() {
    file=$1
    alternative=$2

    if [[ -a $file ]]; then
        source $file
    elif [[ -a $alternative ]]; then
        source $alternative
    fi
}

function cond_eval() {
    cmd=$1
    expression="$2"

    if type $cmd &> /dev/null; then
        result=$(eval $expression)
        eval $result
    fi
}

cond_source /usr/local/opt/fzf/shell/completion.zsh /usr/share/doc/fzf/examples/completion.zsh
cond_source /usr/local/opt/fzf/shell/key-bindings.zsh /usr/share/doc/fzf/examples/key-bindings.zsh
cond_source /usr/share/nvm/init-nvm.sh

cond_eval "pyenv" "pyenv init --path"
cond_eval "direnv" "direnv hook zsh"
cond_eval "zoxide" "zoxide init zsh"

# Setup environment by executing funcs

cond_eval "starship" "starship init zsh"
# if we're in our work environment then load work scripts
# otherwise just load normal scripts
if [[ -a ~/.work ]]; then
    scripts=$SRC/dotfiles/scripts.d/*.bash
else
    scripts=$SRC/dotfiles/scripts.d/^work*.bash
fi

# # in zsh =~ means:
# # = -> perform word splitting
# # ~ -> perform globbing
for file in $=~scripts; do
    source $file
done

