#!/bin/zsh
# vim: set filetype=bash : */ ~

PROG=sg source /Users/william/.sourcegraph/sg.zsh_autocomplete
# The next line enables shell command completion for gcloud.
source "$HOME/google-cloud-sdk/completion.zsh.inc"
source /opt/homebrew/opt/asdf/libexec/asdf.sh

